defmodule BasketWeb.Components.DarkModeToggle do
  @moduledoc """
  A sample component generated by `mix surface.init`.
  """
  use Surface.Component

  import BasketWeb.CoreComponents

  alias Phoenix.LiveView.JS

  def render(assigns) do
    ~F"""
    <div class="justify-center" phx-click={JS.dispatch("toggle-darkmode")}>
      <input type="checkbox" name="light-switch" class="light-switch sr-only">
      <label class="relative cursor-pointer p-2" for="light-switch">
        <.icon name="hero-sun-solid" class="hidden dark:inline-block w-8 h-8 text-yellow-500" />
        <.icon name="hero-moon-solid" class="dark:hidden w-8 h-8 text-blue-200" />
        <span class="sr-only">Switch between light and dark mode</span>
      </label>
    </div>
    """
  end
end
